version: '3.4'

services:
  bancoapi:
    image: ${DOCKER_REGISTRY-}bancoapi
    container_name: ApiBanco
    hostname: ApiBanco
    build:
      context: .
      dockerfile: BancoAPI/Dockerfile
    ports:
    - "500:80"
    networks:
      bancoapi-network:
        ipv4_address: 172.17.0.2
        
  sql_server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: SqlApiBanco
    hostname: SqlApiBanco
    ports: 
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=Strong@Passw0rd
    networks:
      bancoapi-network:
        ipv4_address: 172.17.0.3
        
networks:
    bancoapi-network:
        driver: bridge
   
  