version: '3.4'

services:
  bancoapi:
    image: ${DOCKER_REGISTRY-}bancoapi
    container_name: banco_api
    build:
      context: .
      dockerfile: BancoAPI/Dockerfile
    ports:
     - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=Strong@Passw0rd 

